site_title = "Long Sequence Model and DNA Daily Feed"
limit_days = 30
cache_url = "https://andyjzhao.github.io/dna_arxiv/cache.json"

[[sources]]
limit = 150
category = "q-bio.GN"
title = "Genomics"

[[sources]]
limit = 150
category = "q-bio.BM"
title = "Biomolecules"

[[sources]]
limit = 150
category = "q-bio.MN"
title = "Molecular Networks"
[[sources]]
limit = 150
category = "cs.CL"
title = "Computation and Language"

[[sources]]
limit = 150
category = "cs.LG"
title = "Machine Learning"

[[sources]]
limit = 150
category = "cs.SI"
title = "Social and Information Networks"


[scripts]
highlight_title = "scripts/highlight_title.rhai"
highlight_author = "scripts/highlight_author.rhai"
highlight_conference = "scripts/highlight_conference.rhai"
